web/jobs/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path, re_path

from jobs import views

urlpatterns = [
    # Main pages
    path('', views.JobsTree.as_view(), name='tree'),
    path('<int:pk>/', views.JobPage.as_view(), name='job'),
    path('quantile/<int:pk>/', views.JobQuantilePage.as_view(), name='quantile'),
    path('quantile/', views.JobQuantileSeveralPage.as_view()),
    path('decision_results/<int:pk>/', views.DecisionResults.as_view()),
    path('status/<int:pk>/', views.JobStatus.as_view()),
    path('scatter/<int:job1_id>/<int:job2_id>/', views.JobsScatterPage.as_view(), name='scatter'),

    # Main actions with jobs
    path('remove/', views.RemoveJobsView.as_view()),
    path('clear/', views.ClearJobsView.as_view()),
    path('save_job_copy/<int:pk>/', views.SaveJobCopyView.as_view()),
    path('decision_results_json/<int:pk>/', views.DecisionResultsJson.as_view()),
    path('set_attrs/<int:pk>/', views.SetJobViewAttrs.as_view()),

    # Job form
    re_path(r'^form/(?P<pk>[0-9]+)/(?P<action>edit|copy)/$', views.JobFormPage.as_view(), name='form'),
    path('get_version_data/<int:job_id>/<int:version>/', views.GetJobHistoryData.as_view()),
    path('get_version_roles/<int:job_id>/<int:version>/', views.GetJobHistoryRoles.as_view()),
    path('get_version_files/<int:job_id>/<int:version>/', views.GetJobHistoryFiles.as_view()),

    # Actions with job files
    path('downloadfile/<slug:hash_sum>/', views.DownloadJobFileView.as_view(), name='download_file'),
    path('upload_file/', views.UploadJobFileView.as_view()),
    path('getfilecontent/<slug:hashsum>/', views.GetFileContentView.as_view()),
    path('get_files_diff/<slug:hashsum1>/<slug:hashsum2>/', views.GetFilesDiffView.as_view()),
    path('replace_job_file/<int:job_id>/', views.ReplaceJobFileView.as_view()),
    path('downloadcompetfile/<int:pk>/', views.DownloadFilesForCompetition.as_view(), name='download_file_for_compet'),

    # Download/upload actions
    path('downloadjob/<int:pk>/', views.DownloadJobView.as_view(), name='download'),
    path('downloadjobs/', views.DownloadJobsListView.as_view()),
    path('downloadtrees/', views.DownloadJobsTreeView.as_view()),
    path('upload_jobs/<slug:parent_id>/', views.UploadJobsView.as_view()),
    path('upload_jobs_tree/', views.UploadJobsTreeView.as_view()),

    # Actions with job solving
    path('run_decision/<int:job_id>/', views.StartDecision.as_view()),
    path('stop_decision/<int:pk>/', views.StopDecisionView.as_view()),

    # "Utils"
    path('get_job_field/', views.GetJobFieldView.as_view()),
    path('do_job_has_children/<int:pk>/', views.DoJobHasChildrenView.as_view()),
    path('check_download_access/', views.CheckDownloadAccessView.as_view()),

    # Actions with reports
    path('upload_reports/<int:pk>/', views.UploadReportsView.as_view()),
]

web/marks/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path, re_path

from marks import views

urlpatterns = [
    # Main marks pages
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/$', views.MarkPage.as_view(), name='mark'),
    re_path(r'^(?P<type>unsafe|safe|unknown)/association_changes/(?P<association_id>.*)/$',
            views.AssociationChangesView.as_view()),
    re_path(r'^(?P<type>unsafe|safe|unknown)/$', views.MarksListView.as_view(), name='list'),

    # Mark form
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/(?P<action>create|edit)/$',
            views.MarkFormView.as_view(), name='mark_form'),
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/(?P<action>create|edit)/inline/$',
            views.InlineMarkForm.as_view()),

    # Mark versions views
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/remove_versions/$', views.RemoveVersionsView.as_view()),
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/compare_versions/$', views.CompareVersionsView.as_view()),

    # Download/Upload marks
    re_path(r'^download/(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/$',
            views.DownloadMarkView.as_view(), name='download_mark'),
    re_path(r'^download-preset/(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/$',
            views.DownloadPresetMarkView.as_view(), name='download_preset_mark'),
    path('upload/', views.UploadMarksView.as_view()),
    path('download-all/', views.DownloadAllMarksView.as_view(), name='download_all'),
    path('upload-all/', views.UploadAllMarksView.as_view()),

    # Tags
    path('tags/save_tag/', views.SaveTagView.as_view()),
    re_path(r'^tags/(?P<type>unsafe|safe)/$', views.TagsTreeView.as_view(), name='tags'),
    re_path(r'^tags/(?P<type>unsafe|safe)/download/$', views.DownloadTagsView.as_view(), name='download_tags'),
    re_path(r'^tags/(?P<type>unsafe|safe)/upload/$', views.UploadTagsView.as_view()),
    re_path(r'^tags/(?P<type>unsafe|safe)/get_tag_data/$', views.TagDataView.as_view()),
    re_path(r'^tags/(?P<type>unsafe|safe)/delete/(?P<pk>[0-9]+)/$', views.RemoveTagView.as_view()),
    re_path(r'^(?P<type>unsafe|safe)/tags_data/$', views.MarkTagsView.as_view()),

    # Action with associations
    re_path(r'^association/(?P<type>unsafe|safe|unknown)/(?P<rid>[0-9]+)/(?P<mid>[0-9]+)/(?P<act>confirm|unconfirm)/$',
            views.ChangeAssociationView.as_view()),

    # Utils
    path('delete/', views.DeleteMarksView.as_view()),
    path('get_func_description/<int:pk>/', views.GetFuncDescription.as_view()),
    path('get_progress/<int:pk>/', views.GetProgress.as_view()),
    path('get_last_mark/', views.GetLastMark.as_view()),
    path('get_converted_trace/<int:pk>/', views.GetConvertedTrace.as_view()),
    path('check-unknown-mark/<int:pk>/', views.CheckUnknownMarkView.as_view()),

    # Comments
    path('create-comment/', views.CreateComment.as_view()),
    path('delete-comment/', views.DeleteComment.as_view()),
    path('submit-review/', views.SubmitReview.as_view()),
    path('delete-review/', views.DeleteReview.as_view()),
]

web/users/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path

from users import views

urlpatterns = [
    path('signin/', views.user_signin, name='login'),
    path('signout/', views.user_signout, name='logout'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('profile/<int:user_id>/', views.show_profile, name='show_profile'),
    path('comments/', views.show_comments, name='comments'),
    path('service_signin/', views.service_signin),
    path('service_signout/', views.service_signout),

    # View actions
    path('ajax/get_view/', views.get_view),
    path('ajax/save_view/', views.save_view),
    path('ajax/remove_view/', views.remove_view),
    path('ajax/share_view/', views.share_view),
    path('ajax/preferable_view/', views.preferable_view),
    path('ajax/check_view_name/', views.check_view_name),
]

web/web/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve

from web import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('jobs/', include(('jobs.urls', 'jobs'), namespace='jobs')),
    path('reports/', include(('reports.urls', 'reports'), namespace='reports')),
    path('marks/', include(('marks.urls', 'marks'), namespace='marks')),
    path('service/', include(('service.urls', 'service'), namespace='service')),
    path('tools/', include(('tools.urls', 'tools'), namespace='tools')),
    path('', views.index_page),
    path('population/', views.population, name='population'),
    path('help/<slug:page>/', views.help_pages, name='help'),
    path('get_help_pages/<slug:page>/', views.get_help_pages, name="get_help_pages"),
    path('help/', views.help_pages, name='help'),
    path('media/<path>', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})
]

web/users/models.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

from web.vars import LANGUAGES, USER_ROLES, DATAFORMAT, VIEW_TYPES


class Extended(models.Model):
    user = models.OneToOneField(User, models.CASCADE)
    accuracy = models.SmallIntegerField(default=settings.DEF_USER['accuracy'])
    data_format = models.CharField(max_length=3, choices=DATAFORMAT, default=settings.DEF_USER['dataformat'])
    language = models.CharField(max_length=2, choices=LANGUAGES, default=settings.DEF_USER['language'])
    role = models.CharField(max_length=1, choices=USER_ROLES, default='0')
    timezone = models.CharField(max_length=255, default=settings.DEF_USER['timezone'])
    assumptions = models.BooleanField(default=settings.DEF_USER['assumptions'])
    triangles = models.BooleanField(default=settings.DEF_USER['triangles'])
    coverage_data = models.BooleanField(default=settings.DEF_USER['coverage_data'])

    def __str__(self):
        return self.user.username

    class Meta:
        db_table = 'user_extended'


class View(models.Model):
    author = models.ForeignKey(User, models.CASCADE)
    type = models.CharField(max_length=2, choices=VIEW_TYPES, default=VIEW_TYPES[1][0])
    shared = models.BooleanField(default=False)
    name = models.CharField(max_length=255)
    view = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        db_table = "view"


class PreferableView(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    view = models.ForeignKey(View, models.CASCADE, related_name='+')

    def __str__(self):
        return self.view.name

    class Meta:
        db_table = "user_preferable_view"


class Notifications(models.Model):
    user = models.OneToOneField(User, models.CASCADE)
    settings = models.CharField(max_length=255)
    self_ntf = models.BooleanField(default=True)

web/users/templates/users/edit-profile.html
{% extends 'base.html' %}
{% comment "License" %}
% CVV is a continuous verification visualizer.
% Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
{% endcomment %}

{% load i18n %}
{% load static %}
{% block title %}{% trans 'Settings' %}{% endblock %}

{% block head_block %}
    <script src="{% static 'users/js/users.js' %}"></script>
    <link href="{% static 'users/css/style.css' %}" rel="stylesheet">
{% endblock %}

{% block body_block %}
    <div class="ui olive segment">
        <h3 class="ui header">{% trans 'Settings' %}</h3>
        <form id="user_form" method="post" action="{% url 'users:edit_profile' %}">
            {% csrf_token %}
            <div class="ui grid form">
                <div class="five wide column">
                    <div class="ui teal segment">
                        <h4 class="ui header">{% trans 'Profile' %}</h4>
                        <div class="field required">
                            <label>{{ user_form.first_name.label }}</label>
                            {{ user_form.first_name }}
                            <br>{{ user_form.errors.first_name }}
                        </div>
                        <div class="field required">
                            <label>{{ user_form.last_name.label }}</label>
                            {{ user_form.last_name }}
                            <br>{{ user_form.errors.last_name }}
                        </div>
                        <div class="field">
                            <label>{{ user_form.email.label }}</label>
                            {{ user_form.email }}
                        </div>
                        <div class="field">
                            <label>{{ profile_form.language.label }}</label>
                            {{ profile_form.language }}
                        </div>
                        <div class="field">
                            <label for="timezone">{% trans 'Time zone' %}</label>
                            <select id="timezone" class="ui search dropdown" name="timezone">
                                {% for tmz in timezones %}
                                    <option value="{{ tmz }}"{% if tmz == user.extended.timezone %} selected="selected"{% endif %}>{{ tmz }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="five wide column">
                    <div class="ui teal segment">
                        <h4 class="ui header">{% trans 'Visualization settings' %}</h4>
                        <div class="field">
                            <label>{{ profile_form.accuracy.label }}</label>
                            {{ profile_form.accuracy }}
                            <br>{{ profile_form.errors.accuracy }}
                        </div>
                        <div class="field">
                            <div class="ui checkbox">
                                {{ profile_form.triangles }}
                                <label>{{ profile_form.triangles.label }}<i class="ui help blue icon note-popup" data-content="{% trans 'This setting turns on visualization of error trace closing triangles at the end of each thread.' %}"></i></label>
                            </div>
                        </div>
                        <div class="field" hidden>
                            <label>{{ profile_form.data_format.label }}<i class="ui help blue icon note-popup" data-content="{% trans 'Most of dates are not updated automatically, so human-readable dates could become outdated until you reload page by hand' %}"></i></label>
                            {{ profile_form.data_format }}
                        </div>
                    </div>
                </div>
                <div class="five wide column">
                    <div class="ui red segment">
                        <h4 class="ui header">{% trans 'Change password' %}</h4>
                        <div class="field">
                            <label>{{ user_form.new_password.label }}</label>
                            {{ user_form.new_password }}
                            <br>{{ user_form.errors.new_password }}
                        </div>
                        <div class="field">
                            <label>{{ user_form.retype_password.label }}</label>
                            {{ user_form.retype_password }}
                            <br>{{ user_form.errors.retype_password }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="ui divider"></div>
            <input id="submit_settings" type="submit" class="ui olive button" style="float: right;" name="submit" value="{% trans 'Save' %}">
            <br><br>
        </form>
    </div>
{% endblock %}

web/users/templates/users/login.html
{% extends 'base.html' %}
{% comment "License" %}
% CVV is a continuous verification visualizer.
% Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
{% endcomment %}

{% load i18n %}
{% load static %}
{% block title %}{% trans 'Sign in' %}{% endblock %}

{% block head_block %}
    <script src="{% static 'users/js/login.js' %}"></script>
    <link href="{% static 'users/css/login.css' %}" rel="stylesheet">
{% endblock %}

{% block body_block %}
    <form class="form-signin" role="form" id="login_form" method="post" action="{% url 'users:login' %}{% if request.GET %}?next={{ request.GET.next }}{% endif %}">
        {% csrf_token %}
        <div class="ui violet segment">
        {% if login_errors %}
            <p style="color: #e64d44;">{{ login_errors }}</p>
        {% endif %}
        <div class="ui form large">
            <input placeholder="{% trans 'Username' %}" id="id_username" maxlength="254" name="username" type="text" required autofocus="">
            <br><br>
            <input placeholder="{% trans 'Password' %}" id="id_password" maxlength="254" name="password" type="password" required>
            <input name="next_url" type="hidden">
            <br><br>
            <button class="ui fluid large violet button" type="submit" value="Submit">{% trans 'Sign in' %}</button>
        </div>
        </div>
    </form>
{% endblock %}

web/users/templates/users/showComments.html
{% extends 'base.html' %}
{% comment "License" %}
% CVV is a continuous verification visualizer.
% Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
{% endcomment %}

{% load i18n %}
{% load tz %}
{% load static %}

{% block head_block %}
    <link href="{% static 'marks/css/comments.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}{% trans 'Comments' %}{% endblock %}

{% block body_block %}
<div class="ui basic segment">
    <h1>{% trans 'Comments to unsafe marks' %}</h1>
    <table class="ui celled compact gray selectable table sort-table show-max">
        <thead>
            <tr style="text-align: center">
                <th width="1%">#</th>
                <th>{% trans 'Date' %}</th>
                <th width="1%">{% trans 'Author' %}</th>
                <th>{% trans 'Job' %}</th>
                <th>{% trans 'Description' %}</th>
            </tr>
        </thead>
        <tbody>
        {% for comment in comments %}
            <tr style="text-align: center">
                <td>{{ forloop.counter }}</td>
                <td>{{ comment.date }}</td>
                <td><a href="{% url 'users:show_profile' comment.author.id %}">{{ comment.author.username }}</a></td>
                <td>
                    {% if comment.mark.report %}
                    <a href="{% url 'jobs:job' comment.mark.report.root.job.id %}">{{comment.mark.report.root.job.name}}</a>
                    {% else %}
                    {% trans 'Root report was deleted' %}
                    {% endif %}
                </td>
                <td style="text-align: left">
                    {{ comment.description|safe }}
                    <br>
                    {% if comment.report %}
                    (<a href="{% url 'reports:unsafe' comment.report.id %}">{% trans 'See error trace' %}</a>)
                    {% else %}
                    (<a href="{% url 'marks:mark' 'unsafe' comment.mark.id %}">{% trans 'See mark' %}</a>)
                    {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

web/users/templates/users/showProfile.html
{% extends 'base.html' %}
{% comment "License" %}
% CVV is a continuous verification visualizer.
% Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
{% endcomment %}

{% load i18n %}
{% load tz %}

{% block title %}{% trans 'Profile' %}{% endblock %}

{% block body_block %}
{% if target %}
    <div class="ui grid">
        <div class="three wide column">
            <h3><cite>{{ target.first_name }} {{ target.last_name }}</cite></h3>
            <div class="ui list">
                {% if target.email %}
                    <div class="item"><span style="color: #a7aab4">{% trans 'Email' %}: </span><ins style="color: #507ab4">{{ target.email }}</ins></div>
                {% endif %}
                <div class="item"><span style="color: #a7aab4">{% trans 'Administrator' %}: </span>{% if target.is_superuser %}{% trans 'Yes' %}{% else %}{% trans 'No' %}{% endif %}</div>
                <div class="item"><span style="color: #a7aab4">{% trans 'Role' %}: </span> {{ target.extended.get_role_display }}</div>
                <div class="item"><span style="color: #a7aab4">{% trans 'Time zone' %}: </span> {{ target.extended.timezone }}</div>
                <div class="item"><span style="color: #a7aab4">{% trans 'Language' %}: </span> {{ target.extended.get_language_display }}</div>
            </div>
        </div>
        <div class="thirteen wide column">
            <h2>{% trans 'Last Activity' %}</h2>
            {% if activity|length %}
                <table class="ui selectable celled stripped alternate-color compact table">
                    <thead>
                        <tr>
                            <th width="1%">#</th>
                            <th class="three wide">{% trans 'Date' %}</th>
                            <th>{% trans 'Action Kind' %}</th>
                            <th>{% trans 'Object Type' %}</th>
                            <th>{% trans 'Object Link' %}</th>
                            <th class="four wide">{% trans 'Change Comment' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for act in activity %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ act.date }}</td>
                            <td style="color:{{ act.act_color }}">{{ act.act_type }}</td>
                            <td>{{ act.obj_type }}</td>
                            {% if act.href %}
                                <td><a href="{{ act.href }}">{{ act.obj_link }}</a></td>
                            {% else %}
                                <td>{{ act.obj_link }}</td>
                            {% endif %}
                            {% if act.comment %}
                                <td title="{{ act.comment }}"><small>{{ act.small_comment }}</small></td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% else %}
<h1>{{error}}</h1>
{% endif %}
{% endblock %}