web/jobs/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path, re_path

from jobs import views

urlpatterns = [
    # Main pages
    path('', views.JobsTree.as_view(), name='tree'),
    path('<int:pk>/', views.JobPage.as_view(), name='job'),
    path('quantile/<int:pk>/', views.JobQuantilePage.as_view(), name='quantile'),
    path('quantile/', views.JobQuantileSeveralPage.as_view()),
    path('decision_results/<int:pk>/', views.DecisionResults.as_view()),
    path('status/<int:pk>/', views.JobStatus.as_view()),
    path('scatter/<int:job1_id>/<int:job2_id>/', views.JobsScatterPage.as_view(), name='scatter'),

    # Main actions with jobs
    path('remove/', views.RemoveJobsView.as_view()),
    path('clear/', views.ClearJobsView.as_view()),
    path('save_job_copy/<int:pk>/', views.SaveJobCopyView.as_view()),
    path('decision_results_json/<int:pk>/', views.DecisionResultsJson.as_view()),
    path('set_attrs/<int:pk>/', views.SetJobViewAttrs.as_view()),

    # Job form
    re_path(r'^form/(?P<pk>[0-9]+)/(?P<action>edit|copy)/$', views.JobFormPage.as_view(), name='form'),
    path('get_version_data/<int:job_id>/<int:version>/', views.GetJobHistoryData.as_view()),
    path('get_version_roles/<int:job_id>/<int:version>/', views.GetJobHistoryRoles.as_view()),
    path('get_version_files/<int:job_id>/<int:version>/', views.GetJobHistoryFiles.as_view()),

    # Actions with job files
    path('downloadfile/<slug:hash_sum>/', views.DownloadJobFileView.as_view(), name='download_file'),
    path('upload_file/', views.UploadJobFileView.as_view()),
    path('getfilecontent/<slug:hashsum>/', views.GetFileContentView.as_view()),
    path('get_files_diff/<slug:hashsum1>/<slug:hashsum2>/', views.GetFilesDiffView.as_view()),
    path('replace_job_file/<int:job_id>/', views.ReplaceJobFileView.as_view()),
    path('downloadcompetfile/<int:pk>/', views.DownloadFilesForCompetition.as_view(), name='download_file_for_compet'),

    # Download/upload actions
    path('downloadjob/<int:pk>/', views.DownloadJobView.as_view(), name='download'),
    path('downloadjobs/', views.DownloadJobsListView.as_view()),
    path('downloadtrees/', views.DownloadJobsTreeView.as_view()),
    path('upload_jobs/<slug:parent_id>/', views.UploadJobsView.as_view()),
    path('upload_jobs_tree/', views.UploadJobsTreeView.as_view()),

    # Actions with job solving
    path('run_decision/<int:job_id>/', views.StartDecision.as_view()),
    path('stop_decision/<int:pk>/', views.StopDecisionView.as_view()),

    # "Utils"
    path('get_job_field/', views.GetJobFieldView.as_view()),
    path('do_job_has_children/<int:pk>/', views.DoJobHasChildrenView.as_view()),
    path('check_download_access/', views.CheckDownloadAccessView.as_view()),

    # Actions with reports
    path('upload_reports/<int:pk>/', views.UploadReportsView.as_view()),
]

web/marks/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path, re_path

from marks import views

urlpatterns = [
    # Main marks pages
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/$', views.MarkPage.as_view(), name='mark'),
    re_path(r'^(?P<type>unsafe|safe|unknown)/association_changes/(?P<association_id>.*)/$',
            views.AssociationChangesView.as_view()),
    re_path(r'^(?P<type>unsafe|safe|unknown)/$', views.MarksListView.as_view(), name='list'),

    # Mark form
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/(?P<action>create|edit)/$',
            views.MarkFormView.as_view(), name='mark_form'),
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/(?P<action>create|edit)/inline/$',
            views.InlineMarkForm.as_view()),

    # Mark versions views
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/remove_versions/$', views.RemoveVersionsView.as_view()),
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/compare_versions/$', views.CompareVersionsView.as_view()),

    # Download/Upload marks
    re_path(r'^download/(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/$',
            views.DownloadMarkView.as_view(), name='download_mark'),
    re_path(r'^download-preset/(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/$',
            views.DownloadPresetMarkView.as_view(), name='download_preset_mark'),
    path('upload/', views.UploadMarksView.as_view()),
    path('download-all/', views.DownloadAllMarksView.as_view(), name='download_all'),
    path('upload-all/', views.UploadAllMarksView.as_view()),

    # Tags
    path('tags/save_tag/', views.SaveTagView.as_view()),
    re_path(r'^tags/(?P<type>unsafe|safe)/$', views.TagsTreeView.as_view(), name='tags'),
    re_path(r'^tags/(?P<type>unsafe|safe)/download/$', views.DownloadTagsView.as_view(), name='download_tags'),
    re_path(r'^tags/(?P<type>unsafe|safe)/upload/$', views.UploadTagsView.as_view()),
    re_path(r'^tags/(?P<type>unsafe|safe)/get_tag_data/$', views.TagDataView.as_view()),
    re_path(r'^tags/(?P<type>unsafe|safe)/delete/(?P<pk>[0-9]+)/$', views.RemoveTagView.as_view()),
    re_path(r'^(?P<type>unsafe|safe)/tags_data/$', views.MarkTagsView.as_view()),

    # Action with associations
    re_path(r'^association/(?P<type>unsafe|safe|unknown)/(?P<rid>[0-9]+)/(?P<mid>[0-9]+)/(?P<act>confirm|unconfirm)/$',
            views.ChangeAssociationView.as_view()),

    # Utils
    path('delete/', views.DeleteMarksView.as_view()),
    path('get_func_description/<int:pk>/', views.GetFuncDescription.as_view()),
    path('get_progress/<int:pk>/', views.GetProgress.as_view()),
    path('get_last_mark/', views.GetLastMark.as_view()),
    path('get_converted_trace/<int:pk>/', views.GetConvertedTrace.as_view()),
    path('check-unknown-mark/<int:pk>/', views.CheckUnknownMarkView.as_view()),

    # Comments
    path('create-comment/', views.CreateComment.as_view()),
    path('delete-comment/', views.DeleteComment.as_view()),
    path('submit-review/', views.SubmitReview.as_view()),
    path('delete-review/', views.DeleteReview.as_view()),
]

web/reports/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path

from reports import views

urlpatterns = [
    # ReportComponent page
    path('component/<int:pk>/', views.ReportComponentView.as_view(), name='component'),
    path('log/<int:report_id>/', views.ComponentLogView.as_view(), name='log'),
    path('logcontent/<int:report_id>/', views.ComponentLogContent.as_view()),
    path('attrdata/<int:pk>/', views.AttrDataFileView.as_view()),
    path('attrdata-content/<int:pk>/', views.AttrDataContentView.as_view()),
    path('component/<int:pk>/download_files/', views.DownloadVerifierFiles.as_view(), name='download_files'),

    # List of verdicts
    path('component/<int:report_id>/safes/', views.SafesListView.as_view(), name='safes'),
    path('component/<int:report_id>/unsafes/', views.UnsafesListView.as_view(), name='unsafes'),
    path('component/<int:report_id>/unknowns/', views.UnknownsListView.as_view(), name='unknowns'),

    # Pages of verdicts
    path('safe/<int:pk>/', views.ReportSafeView.as_view(), name='safe'),
    path('unknown/<int:pk>/', views.ReportUnknownView.as_view(), name='unknown'),
    path('unsafe/<int:pk>/', views.ReportUnsafeViewById.as_view(), name='unsafe'),
    path('unsafe/<slug:trace_id>/', views.ReportUnsafeView.as_view(), name='unsafe'),
    path('unsafe/<slug:trace_id>/fullscreen/', views.FullscreenReportUnsafe.as_view(), name='unsafe_fullscreen'),
    path('unsafe/<slug:trace_id>/edit/', views.EditReportUnsafe.as_view(), name='unsafe_edit'),
    path('get_source/<int:id>/', views.SourceCodeView.as_view()),
    path('download-error-trace/<int:unsafe_id>/', views.DownloadErrorTrace.as_view(), name='download_error_trace'),
    path('download-error-trace-html/<int:unsafe_id>/', views.DownloadErrorTraceHtml.as_view(),
         name='download_error_trace_html'),
    path('download-proof/<int:safe_id>/', views.DownloadProof.as_view(), name='download_proof'),
    path('download-proof-html/<int:safe_id>/', views.DownloadProofHtml.as_view(), name='download_proof_html'),

    # Reports comparison
    path('comparison/<int:job1_id>/<int:job2_id>/', views.ReportsComparisonView.as_view(), name='comparison'),
    path('comparison/<int:job_id>/', views.ReportsComparisonNodeView.as_view(), name='comparison'),
    path('comparison-data/<int:pk>/', views.ReportsComparisonNodeDataView.as_view()),

    # Coverage
    path('coverage/<int:report_id>/', views.CoverageView.as_view(), name='coverage'),
    path('coverage-light/<int:report_id>/', views.CoverageLightView.as_view(), name='coverage_light'),
    path('get-coverage-src/<int:archive_id>/', views.CoverageSrcView.as_view()),
    path('download_coverage/<int:pk>/', views.DownloadCoverageView.as_view(), name='download_coverage'),

    # Utils
    path('upload/', views.UploadReportView.as_view()),
    path('clear_verification_files/<int:job_id>/', views.ClearVerificationFiles.as_view()),
    path('unsafe/<int:pk>/apply/', views.UnsafeApplyView.as_view()),
    path('unsafe/<int:pk>/upload/', views.UnsafeUploadView.as_view()),
    path('unsafe/<int:pk>/cancel/', views.UnsafeCancelView.as_view())
]

web/users/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path

from users import views

urlpatterns = [
    path('signin/', views.user_signin, name='login'),
    path('signout/', views.user_signout, name='logout'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('profile/<int:user_id>/', views.show_profile, name='show_profile'),
    path('comments/', views.show_comments, name='comments'),
    path('service_signin/', views.service_signin),
    path('service_signout/', views.service_signout),

    # View actions
    path('ajax/get_view/', views.get_view),
    path('ajax/save_view/', views.save_view),
    path('ajax/remove_view/', views.remove_view),
    path('ajax/share_view/', views.share_view),
    path('ajax/preferable_view/', views.preferable_view),
    path('ajax/check_view_name/', views.check_view_name),
]

web/web/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve

from web import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('jobs/', include(('jobs.urls', 'jobs'), namespace='jobs')),
    path('reports/', include(('reports.urls', 'reports'), namespace='reports')),
    path('marks/', include(('marks.urls', 'marks'), namespace='marks')),
    path('service/', include(('service.urls', 'service'), namespace='service')),
    path('tools/', include(('tools.urls', 'tools'), namespace='tools')),
    path('', views.index_page),
    path('population/', views.population, name='population'),
    path('help/<slug:page>/', views.help_pages, name='help'),
    path('get_help_pages/<slug:page>/', views.get_help_pages, name="get_help_pages"),
    path('help/', views.help_pages, name='help'),
    path('media/<path>', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})
]

web/marks/templates/marks/Comments.html
{% comment "License" %}
% CVV is a continuous verification visualizer.
% Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
{% endcomment %}

{% load i18n %}

{% load static %}
<link href="{% static 'marks/css/comments.css' %}" rel="stylesheet">
<script type="text/javascript" src="{% static 'marks/js/comments.js' %}"></script>

<div class="ui gray segment fluid">
    <h4 class="ui top left attached gray label">{% trans 'Comments' %}</h4>
    <div id="comments_root_{{mark_id}}" class="ui minimal comments" style="max-width: 100%">
        {% for comment in comments %}
        <div id="comment_{{comment.3}}" class="comment{% if not comment.5 and show_short_comments_list %} collapsed{% endif %}">
            <div class="content">
                <a href="{% url 'users:show_profile' comment.0.id %}" class="author">{{comment.0.username}}</a>
                <div class="metadata">
                    <span class="date">{{comment.1}}</span>
                </div>
                <div id="comment_text_{{comment.3}}" class="text">{{comment.2|safe}}</div>
                <div class="actions" style="align-items: left">
                    {% if comment.6 %}
                    <a class="show" href="{% url 'reports:unsafe' comment.6.id %}">{% trans 'Show original report' %}</a>
                    {% endif %}
                    <a class="reply" onclick="reply_comment('{{comment.3}}', '{{comment.0.username}}', '{{mark_id}}')">{% trans 'Reply' %}</a>
                    {% if comment.4 %}
                    <a class="edit" onclick="edit_comment({{comment.3}}, {{mark_id}})">{% trans 'Edit' %}</a>
                    <a class="delete" onclick="delete_comment({{comment.3}}, {{mark_id}})">{% trans 'Delete' %}</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
        {% if comments|length > 3 and show_short_comments_list %}
            <div id="show_comments_btn_{{mark_id}}" class="ui icon small basic compact button" onclick="show_comments({{mark_id}})">{% trans 'Show all' %}</div>
        {% endif %}
        <form class="ui reply form">
            <div class="field">
                <textarea id="new_comment_field_{{mark_id}}" placeholder="{% trans 'Comment' %}..." rows="2" style="resize:none; height: 100%" maxlength="512"></textarea>
            </div>
            <div class="ui green button small" onclick="new_comment({{mark_id}})">
                <i class="icon edit"></i> {% trans 'Create comment' %}
            </div>
        </form>
    </div>
</div>
<input id="edit_comment_id_{{mark_id}}" type="hidden" value="">

web/marks/templates/marks/MarkProgress.html
{% comment "License" %}
%
% CVV is a continuous verification visualizer.
% Copyright (c) 2019-2023 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
{% endcomment %}
{% load i18n %}

<div id="progress_bar_popup" class="ui modal">
    <div class="header"><h1 align="center">{% trans 'Progress of mark application' %}</h1></div>
    <div class="content">
        <div class="ui indicating progress active" data-value="0" data-total="100" id="progress_bar">
            <div class="bar">
                <div class="progress"></div>
            </div>
        </div>
        <div class="ui purple segment">
            <h3>{% trans 'Mark identifier' %}:
                <span id="progress_bar_mark_id"></span>
            </h3>
        </div>
        <div class="ui purple segment">
            <h3>{% trans 'Wall time of mark application' %}:
                <span id="progress_bar_mark_wall_time">0</span>
                {% trans 's' %}
            </h3>
        </div>
        <div class="ui purple segment">
            <h3>{% trans 'Number of successful applications' %}:
                <span id="progress_bar_mark_applied">0</span>
            </h3>
        </div>
    </div>
</div>

web/marks/templates/marks/SaveMarkResult.html
{% extends 'base.html' %}
{% comment "License" %}
% CVV is a continuous verification visualizer.
% Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
{% endcomment %}

{% load i18n %}
{% load static %}

{% block title %}{% trans 'Total expert evaluation changes' %}{% endblock %}

{% block head_block %}
    <link href="{% static 'marks/css/mark.css' %}" rel="stylesheet">
    <link href="{% static 'marks/css/tagsmap.css' %}" rel="stylesheet">
    {% block mark_head_block %}{% endblock %}
{% endblock %}

{% block body_block %}
    <button type="button" class="ui tiny violet button" id="view_show_form_btn_{{ TableData.view.type }}" style="float:right;margin-right: 10px;">{{ TableData.view.viewtitle }}</button>
    <div class="ui breadcrumb">
        {% if job_id %}
            <a href="{% url 'jobs:job' job_id %}">{% trans 'Report' %}</a>
        {% endif %}
        {% if root_report_id %}
            <i class="right arrow icon divider"></i>
            {% if type == 'unsafe' %}
            <a href="{% url 'reports:unsafes' root_report_id %}">{% trans 'List of all error traces' %}</a>
            <i class="right arrow icon divider"></i>
            <a href="{% url 'reports:unsafes' root_report_id %}?verdict=5">{% trans 'List of unmarked error traces' %}</a>
            {% elif type == 'safe' %}
            <a href="{% url 'reports:safes' root_report_id %}">{% trans 'List of all safes' %}</a>
            {% else %}
            <a href="{% url 'reports:unknowns' root_report_id %}">{% trans 'List of all unknowns' %}</a>
            {% endif %}
        {% endif %}
        {% if report_id %}
            <i class="right arrow icon divider"></i>
            {% if type == 'unsafe' %}
            <a href="{% url 'reports:unsafe' report_id %}">{% trans 'Error trace' %}</a>
            {% elif type == 'safe' %}
            <a href="{% url 'reports:safe' report_id %}">{% trans 'Safe' %}</a>
            {% else %}
            <a href="{% url 'reports:unknown' report_id %}">{% trans 'Problem' %}</a>
            {% endif %}
        {% endif %}
    </div>
    <br>
    <div id="view_form_segment_{{ TableData.view.type }}" class="ui form yellow segment" style="display: none">
        {% include TableData.view.template with view=TableData.view selected_columns=TableData.selected_columns available_columns=TableData.available_columns verdicts=TableData.verdicts %}
    </div>
    <br>
    {% if TableData.values|length %}
        <table class="ui celled compact pink selectable table sort-table show-min" width="100%">
            <thead>
                {% for column_row in TableData.header %}
                    <tr style="text-align: center">
                    {% for coldata in column_row %}
                        <th colspan="{{ coldata.columns }}" rowspan="{{ coldata.rows }}">{{ coldata.title }}</th>
                    {% endfor %}
                    </tr>
                {% endfor %}
            </thead>
            <tbody>
                {% for row_data in TableData.values %}
                    <tr style="text-align: center">
                        {% for v in row_data %}
                            <td>
                                {% if v.href %}
                                    <a class="black-link" href="{{ v.href }}">{{ v.value }}</a>
                                {% else %}
                                    {% if v.color %}
                                        <span {% if v.color %} style="color: {{ v.color }}"{% endif %}>{{ v.value|safe }}</span>
                                    {% else %}
                                        <span {% if v.color %} style="color: {{ v.color }}"{% endif %}>
                                            <a class="black-link" href="{{ row_data.0.href }}">{{ v.value|safe }}</a>
                                        </span>
                                    {% endif %}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {%  endfor %}
            </tbody>
        </table>
    {% else %}
        <h1 class="header" style="text-align:center;">{% trans 'No changes with total expert evaluations or the view has filtered all results' %}</h1>
    {% endif %}
    <br>
    {% if wall_time or applied_reports %}
    <div class="ui horizontal segments">
        {% if wall_time %}
        <div class="ui segment">{% trans 'Wall time of mark application' %}: {{wall_time}} {% trans 's' %}</div>
        {% endif %}
        {% if applied_reports %}
        <div class="ui segment">{% trans 'Number of successful applications' %}: {{applied_reports}}</div>
        {% endif %}
    </div>
    {% endif %}
    <a href="{{ TableData.href }}" class="ui tiny olive button" style="float:right;margin-right: 10px;">{% trans 'Show mark' %}</a>
{% endblock %}