web/jobs/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path, re_path

from jobs import views

urlpatterns = [
    # Main pages
    path('', views.JobsTree.as_view(), name='tree'),
    path('<int:pk>/', views.JobPage.as_view(), name='job'),
    path('quantile/<int:pk>/', views.JobQuantilePage.as_view(), name='quantile'),
    path('quantile/', views.JobQuantileSeveralPage.as_view()),
    path('decision_results/<int:pk>/', views.DecisionResults.as_view()),
    path('status/<int:pk>/', views.JobStatus.as_view()),
    path('scatter/<int:job1_id>/<int:job2_id>/', views.JobsScatterPage.as_view(), name='scatter'),

    # Main actions with jobs
    path('remove/', views.RemoveJobsView.as_view()),
    path('clear/', views.ClearJobsView.as_view()),
    path('save_job_copy/<int:pk>/', views.SaveJobCopyView.as_view()),
    path('decision_results_json/<int:pk>/', views.DecisionResultsJson.as_view()),
    path('set_attrs/<int:pk>/', views.SetJobViewAttrs.as_view()),

    # Job form
    re_path(r'^form/(?P<pk>[0-9]+)/(?P<action>edit|copy)/$', views.JobFormPage.as_view(), name='form'),
    path('get_version_data/<int:job_id>/<int:version>/', views.GetJobHistoryData.as_view()),
    path('get_version_roles/<int:job_id>/<int:version>/', views.GetJobHistoryRoles.as_view()),
    path('get_version_files/<int:job_id>/<int:version>/', views.GetJobHistoryFiles.as_view()),

    # Actions with job files
    path('downloadfile/<slug:hash_sum>/', views.DownloadJobFileView.as_view(), name='download_file'),
    path('upload_file/', views.UploadJobFileView.as_view()),
    path('getfilecontent/<slug:hashsum>/', views.GetFileContentView.as_view()),
    path('get_files_diff/<slug:hashsum1>/<slug:hashsum2>/', views.GetFilesDiffView.as_view()),
    path('replace_job_file/<int:job_id>/', views.ReplaceJobFileView.as_view()),
    path('downloadcompetfile/<int:pk>/', views.DownloadFilesForCompetition.as_view(), name='download_file_for_compet'),

    # Download/upload actions
    path('downloadjob/<int:pk>/', views.DownloadJobView.as_view(), name='download'),
    path('downloadjobs/', views.DownloadJobsListView.as_view()),
    path('downloadtrees/', views.DownloadJobsTreeView.as_view()),
    path('upload_jobs/<slug:parent_id>/', views.UploadJobsView.as_view()),
    path('upload_jobs_tree/', views.UploadJobsTreeView.as_view()),

    # Actions with job solving
    path('run_decision/<int:job_id>/', views.StartDecision.as_view()),
    path('stop_decision/<int:pk>/', views.StopDecisionView.as_view()),

    # "Utils"
    path('get_job_field/', views.GetJobFieldView.as_view()),
    path('do_job_has_children/<int:pk>/', views.DoJobHasChildrenView.as_view()),
    path('check_download_access/', views.CheckDownloadAccessView.as_view()),

    # Actions with reports
    path('upload_reports/<int:pk>/', views.UploadReportsView.as_view()),
]

web/marks/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path, re_path

from marks import views

urlpatterns = [
    # Main marks pages
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/$', views.MarkPage.as_view(), name='mark'),
    re_path(r'^(?P<type>unsafe|safe|unknown)/association_changes/(?P<association_id>.*)/$',
            views.AssociationChangesView.as_view()),
    re_path(r'^(?P<type>unsafe|safe|unknown)/$', views.MarksListView.as_view(), name='list'),

    # Mark form
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/(?P<action>create|edit)/$',
            views.MarkFormView.as_view(), name='mark_form'),
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/(?P<action>create|edit)/inline/$',
            views.InlineMarkForm.as_view()),

    # Mark versions views
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/remove_versions/$', views.RemoveVersionsView.as_view()),
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/compare_versions/$', views.CompareVersionsView.as_view()),

    # Download/Upload marks
    re_path(r'^download/(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/$',
            views.DownloadMarkView.as_view(), name='download_mark'),
    re_path(r'^download-preset/(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/$',
            views.DownloadPresetMarkView.as_view(), name='download_preset_mark'),
    path('upload/', views.UploadMarksView.as_view()),
    path('download-all/', views.DownloadAllMarksView.as_view(), name='download_all'),
    path('upload-all/', views.UploadAllMarksView.as_view()),

    # Tags
    path('tags/save_tag/', views.SaveTagView.as_view()),
    re_path(r'^tags/(?P<type>unsafe|safe)/$', views.TagsTreeView.as_view(), name='tags'),
    re_path(r'^tags/(?P<type>unsafe|safe)/download/$', views.DownloadTagsView.as_view(), name='download_tags'),
    re_path(r'^tags/(?P<type>unsafe|safe)/upload/$', views.UploadTagsView.as_view()),
    re_path(r'^tags/(?P<type>unsafe|safe)/get_tag_data/$', views.TagDataView.as_view()),
    re_path(r'^tags/(?P<type>unsafe|safe)/delete/(?P<pk>[0-9]+)/$', views.RemoveTagView.as_view()),
    re_path(r'^(?P<type>unsafe|safe)/tags_data/$', views.MarkTagsView.as_view()),

    # Action with associations
    re_path(r'^association/(?P<type>unsafe|safe|unknown)/(?P<rid>[0-9]+)/(?P<mid>[0-9]+)/(?P<act>confirm|unconfirm)/$',
            views.ChangeAssociationView.as_view()),

    # Utils
    path('delete/', views.DeleteMarksView.as_view()),
    path('get_func_description/<int:pk>/', views.GetFuncDescription.as_view()),
    path('get_progress/<int:pk>/', views.GetProgress.as_view()),
    path('get_last_mark/', views.GetLastMark.as_view()),
    path('get_converted_trace/<int:pk>/', views.GetConvertedTrace.as_view()),
    path('check-unknown-mark/<int:pk>/', views.CheckUnknownMarkView.as_view()),

    # Comments
    path('create-comment/', views.CreateComment.as_view()),
    path('delete-comment/', views.DeleteComment.as_view()),
    path('submit-review/', views.SubmitReview.as_view()),
    path('delete-review/', views.DeleteReview.as_view()),
]

web/reports/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path

from reports import views

urlpatterns = [
    # ReportComponent page
    path('component/<int:pk>/', views.ReportComponentView.as_view(), name='component'),
    path('log/<int:report_id>/', views.ComponentLogView.as_view(), name='log'),
    path('logcontent/<int:report_id>/', views.ComponentLogContent.as_view()),
    path('attrdata/<int:pk>/', views.AttrDataFileView.as_view()),
    path('attrdata-content/<int:pk>/', views.AttrDataContentView.as_view()),
    path('component/<int:pk>/download_files/', views.DownloadVerifierFiles.as_view(), name='download_files'),

    # List of verdicts
    path('component/<int:report_id>/safes/', views.SafesListView.as_view(), name='safes'),
    path('component/<int:report_id>/unsafes/', views.UnsafesListView.as_view(), name='unsafes'),
    path('component/<int:report_id>/unknowns/', views.UnknownsListView.as_view(), name='unknowns'),

    # Pages of verdicts
    path('safe/<int:pk>/', views.ReportSafeView.as_view(), name='safe'),
    path('unknown/<int:pk>/', views.ReportUnknownView.as_view(), name='unknown'),
    path('unsafe/<int:pk>/', views.ReportUnsafeViewById.as_view(), name='unsafe'),
    path('unsafe/<slug:trace_id>/', views.ReportUnsafeView.as_view(), name='unsafe'),
    path('unsafe/<slug:trace_id>/fullscreen/', views.FullscreenReportUnsafe.as_view(), name='unsafe_fullscreen'),
    path('unsafe/<slug:trace_id>/edit/', views.EditReportUnsafe.as_view(), name='unsafe_edit'),
    path('get_source/<int:id>/', views.SourceCodeView.as_view()),
    path('download-error-trace/<int:unsafe_id>/', views.DownloadErrorTrace.as_view(), name='download_error_trace'),
    path('download-error-trace-html/<int:unsafe_id>/', views.DownloadErrorTraceHtml.as_view(),
         name='download_error_trace_html'),
    path('download-proof/<int:safe_id>/', views.DownloadProof.as_view(), name='download_proof'),
    path('download-proof-html/<int:safe_id>/', views.DownloadProofHtml.as_view(), name='download_proof_html'),

    # Reports comparison
    path('comparison/<int:job1_id>/<int:job2_id>/', views.ReportsComparisonView.as_view(), name='comparison'),
    path('comparison/<int:job_id>/', views.ReportsComparisonNodeView.as_view(), name='comparison'),
    path('comparison-data/<int:pk>/', views.ReportsComparisonNodeDataView.as_view()),

    # Coverage
    path('coverage/<int:report_id>/', views.CoverageView.as_view(), name='coverage'),
    path('coverage-light/<int:report_id>/', views.CoverageLightView.as_view(), name='coverage_light'),
    path('get-coverage-src/<int:archive_id>/', views.CoverageSrcView.as_view()),
    path('download_coverage/<int:pk>/', views.DownloadCoverageView.as_view(), name='download_coverage'),

    # Utils
    path('upload/', views.UploadReportView.as_view()),
    path('clear_verification_files/<int:job_id>/', views.ClearVerificationFiles.as_view()),
    path('unsafe/<int:pk>/apply/', views.UnsafeApplyView.as_view()),
    path('unsafe/<int:pk>/upload/', views.UnsafeUploadView.as_view()),
    path('unsafe/<int:pk>/cancel/', views.UnsafeCancelView.as_view())
]

web/users/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path

from users import views

urlpatterns = [
    path('signin/', views.user_signin, name='login'),
    path('signout/', views.user_signout, name='logout'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('profile/<int:user_id>/', views.show_profile, name='show_profile'),
    path('comments/', views.show_comments, name='comments'),
    path('service_signin/', views.service_signin),
    path('service_signout/', views.service_signout),

    # View actions
    path('ajax/get_view/', views.get_view),
    path('ajax/save_view/', views.save_view),
    path('ajax/remove_view/', views.remove_view),
    path('ajax/share_view/', views.share_view),
    path('ajax/preferable_view/', views.preferable_view),
    path('ajax/check_view_name/', views.check_view_name),
]

web/web/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve

from web import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('jobs/', include(('jobs.urls', 'jobs'), namespace='jobs')),
    path('reports/', include(('reports.urls', 'reports'), namespace='reports')),
    path('marks/', include(('marks.urls', 'marks'), namespace='marks')),
    path('service/', include(('service.urls', 'service'), namespace='service')),
    path('tools/', include(('tools.urls', 'tools'), namespace='tools')),
    path('', views.index_page),
    path('population/', views.population, name='population'),
    path('help/<slug:page>/', views.help_pages, name='help'),
    path('get_help_pages/<slug:page>/', views.get_help_pages, name="get_help_pages"),
    path('help/', views.help_pages, name='help'),
    path('media/<path>', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})
]

web/reports/templates/reports/ETV_HideLink.html
{% comment "License" %}
% CVV is a continuous verification visualizer.
% Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
{% endcomment %}{% if l.hide_id %}{% if not l.collapsed %}<a id="{{ l.hide_id }}" class="ETV_ShowCode"><i class="mini icon unhide"></i></a>{% else %}<a id="{{ l.hide_id }}" class="ETV_HideLink"><i class="mini icon violet caret {% if l.collapsed %}right{% else %}down{% endif %}"></i></a>{% endif %}{% endif %}

web/reports/templates/reports/UnsafeContent.html
{% comment "License" %}
% CVV is a continuous verification visualizer.
% Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
{% endcomment %}

{% load i18n %}
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
{% if standalone_html %}
    <span id="standalone" hidden>true</span>
    <style>
        body {
            padding: 5px 5px 5px 5px;
        }
    </style>
{% endif %}

<div id="etv" class="ui {% if etv.type == 'correctness' %}green{% else %}red{% endif %} segment {% if fullscreen %} fullscreen{% endif %}">
    <div id="etv-trace">
        <div>
            <div class="ui grid equal width columns">
                <div class="column" style="margin: 2px;">
                    {% if etv.type == 'correctness' %}
                    <div class="ui buttons icon tiny green">
                        <button class="ui tiny button icon note-popup" id="toggle_eyes" data-content="{% trans 'Toggle top level elements' %}">
                            <i class="ui eye icon"></i>
                        </button>
                        <button class="ui tiny button icon note-popup" id="toggle_functions" data-content="{% trans 'Toggle all elements' %}">
                            <i class="ui sitemap icon"></i>
                        </button>
                        <button class="ui tiny button icon note-popup" id="toggle_specific_funcs" data-content="{% trans 'Show only specified variable usages' %}">
                            <i class="ui search icon"></i>
                        </button>
                        <button class="ui tiny button icon note-popup" id="toggle_partial_cond" data-content="{% trans 'Show only partially covered conditions' %}">
                            <i class="ui compress icon"></i>
                        </button>
                    </div>
                    {% else %}
                    <div class="ui buttons icon tiny red">
                        <button class="ui tiny button icon note-popup" id="toggle_eyes" data-content="{% trans 'Toggle functions from call stack' %}">
                            <i class="ui eye icon"></i>
                        </button>
                        <button class="ui tiny button icon note-popup" id="toggle_functions" data-content="{% trans 'Toggle all functions' %}">
                            <i class="ui sitemap icon"></i>
                        </button>
                        <button class="ui tiny button icon note-popup" id="toggle_notes" data-content="{% trans 'Toggle notes code' %}">
                            <i class="ui comments outline icon"></i>
                        </button>
                        <button class="ui tiny button icon note-popup" id="toggle_hidden_notes" data-content="{% trans 'Toggle hidden notes' %}">
                            <i class="ui comment outline icon"></i>
                        </button>
                    </div>
                    {% endif %}
                </div>
                <div class="column center aligned" style="margin: 10px;white-space: nowrap;">
                    {% if etv.type == 'correctness' %}
                    <h3>{% trans 'Correctness witness' %}</h3>
                    {% else %}
                    <h3>{% trans 'Error trace' %}</h3>
                    {% endif %}
                </div>
                <div class="column right aligned" style="margin: 2px;">
                    {% if not standalone_html %}
                    {% if etv.type == 'correctness' %}
                    <div class="ui buttons icon tiny">
                        <a class="ui tiny button violet note-popup" href="{% url 'reports:download_proof_html' report.pk %}" data-content="{% trans 'Download standalone proof' %}">
                            <i class="ui download icon"></i>
                        </a>
                        <a class="ui tiny button violet note-popup" href="{% url 'reports:download_proof' report.pk %}" data-content="{% trans 'Download proof internal representation' %}">
                            <i class="ui save outline icon"></i>
                        </a>
                    </div>
                    {% else %}
                    <div class="ui buttons icon tiny">
                        <a class="ui tiny button violet note-popup" href="{% url 'reports:download_error_trace_html' report.pk %}" data-content="{% trans 'Download standalone trace' %}">
                            <i class="ui download icon"></i>
                        </a>
                        <a class="ui tiny button violet note-popup" href="{% url 'reports:download_error_trace' report.pk %}" data-content="{% trans 'Download error trace internal representation' %}">
                            <i class="ui save outline icon"></i>
                        </a>
                        {% if not edit and is_modifiable %}
                        <button id="upload_edited_trace" class="ui tiny button violet note-popup" data-content="{% trans 'Upload edited error trace' %}">
                            <i class="ui upload icon"></i>
                        </button>
                        <a class="ui tiny button violet note-popup" href="{% url 'reports:unsafe_edit' report.trace_id %}" data-content="{% trans 'Edit' %}">
                            <i class="ui edit icon"></i>
                        </a>
                        {% endif %}
                        {% if edit %}
                        {% if is_edited_exist %}
                        <button class="ui button tiny red note-popup" id="cancel_changes" data-content="{% trans 'Remove edited error trace' %}">
                            <i class="ui fire icon"></i>
                        </button>
                        {% endif %}
                        <button class="ui tiny button green note-popup" id="apply_changes" data-content="{% trans 'Apply' %}">
                            <i class="ui check circle icon"></i>
                        </button>
                        <a class="ui tiny button violet note-popup" href="{% url 'reports:unsafe' report.trace_id %}" data-content="{% trans 'Cancel' %}">
                            <i class="ui undo icon"></i>
                        </a>
                        {% endif %}
                        {% if not fullscreen %}
                        <a class="ui tiny button violet note-popup" href="{% url 'reports:unsafe_fullscreen' report.trace_id %}" data-content="{% trans 'Full screen mode' %}">
                            <i class="ui icon expand"></i>
                        </a>
                        {% elif not edit %}
                        <a class="ui icon tiny button violet note-popup" href="{% url 'reports:unsafe' report.trace_id %}" data-content="{% trans 'Close' %}">
                            <i class="remove icon"></i>
                        </a>
                        {% endif %}
                    </div>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
            {% if etv %}
                {% include 'reports/ErrorTrace.html' with etv=etv %}
            {% else %}
                <div class="ui divider"></div>
                <h2 class="ui red header" style="margin: 10px;">{% trans "Couldn't visualize the error trace" %}</h2>
            {% endif %}
        </div>
    </div>
    <div id="etv-source"{% if include_assumptions %} style="height:70%;"{% endif %}>
        <div style="margin: 10px;">
            <div class="ETVTitleBlock">
                <h4 id="ETVSourceTitle" class="header" data-position="top right" style="padding-bottom: 7px;float: left;"></h4>
                <div class="ui popup very wide">
                    <p id="ETVSourceTitleFull"></p>
                </div>
            </div>
            <div class="filecontent ETV_source_code" id="ETV_source_code" {% if etv.type == 'correctness' %}style="border-top: 1px solid green;"{% endif %}></div>
            {% for filename, content in src.items %}
                <div class="filecontent ETV_source_code" style="display: none" id="src_files{{filename}}">{{ content }}</div>
            {%endfor%}
        </div>
    </div>
    <div id="{% if etv.type == 'correctness' %}etv-divider-safe{% else %}etv-divider{% endif %}"></div>
    {% if include_assumptions %}
        <div id="etv-assumes">
            <div id="ETV_assumes">
            </div>
        </div>
        <div id="etv-divider-2"></div>
    {% endif %}
</div>

{% if etv.warnings %}
<div class="ui red segment fluid">
    <div class="ui header red" onclick="toggle_by_id('etv_warnings_toggle')" style="cursor:pointer;">
        <b style="color: red">
            {% trans 'Warning: some elements are missing' %}
        </b>
    </div>
    <div id="etv_warnings_toggle" hidden>
        <div class="ui list ordered">
            {% for warn in etv.warnings %}
            <div class="item">
                {{warn}}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<br>
{% endif %}

{% if etv %}
    {% if etv.attributes|length %}
        <div id="etv-attributes" class="ui popup very wide" style="white-space: nowrap;">
            <div class="ui grid">
                <div class="sixteen wide column left aligned">
                    {% for attribute in etv.attributes %}
                        <span class="ui violet header small">{{ attribute.0 }}</span>: <span class="small">{{ attribute.1 }}</span><br>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}

    <div id="upload_edited_trace_popup" class="ui modal">
        <div class="header">{% trans 'Upload edited error trace' %}</div>
        <div class="content">
            <div class="ui grid">
                <div class="four wide column right aligned">
                    <span class="ui violet button btn-file">{% trans 'Browse' %}<input id="upload_edited_trace_input" type="file"></span>
                </div>
                <div class="twelve wide column">
                    <span id="upload_edited_trace_filename" class="italic"></span>
                </div>
            </div>
        </div>
        <div class="actions">
            <button id="upload_edited_trace_start" type="button" class="ui positive left button">{% trans 'Upload' %}</button>
            <button id="upload_edited_trace_cancel" type="button" class="ui blue button">{% trans 'Cancel' %}</button>
        </div>
    </div>

    <span id="error___line_not_found" hidden>{% trans 'Could not find the specified line' %}</span>
    <span id="error___no_selected_line" hidden>{% trans 'Please, select the line first' %}</span>
    <span id="witness_type" hidden>{{etv.type}}</span>
{% endif %}

<div id="form_toggle_specific_funcs" class="ui modal">
    <h3 class="ui header center aligned">{% trans 'Show only specified variable usages' %}</h3>
    <div class="content">
        <div class="ui form">
            <div class="fields">
                <div class="eight wide field">
                    <label for="form_specific_funcs">{% trans 'Enter variable name fragment' %}</label>
                    <input id="form_specific_funcs" type="text">
                </div>
            </div>
        </div>
    </div>
    <div class="actions">
        <button id="form_toggle_specific_funcs_ok" type="button" class="ui positive left button">{% trans 'OK' %}</button>
        <button id="form_toggle_specific_funcs_cancel" type="button" class="ui blue button">{% trans 'Cancel' %}</button>
    </div>
</div>