web/jobs/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path, re_path

from jobs import views

urlpatterns = [
    # Main pages
    path('', views.JobsTree.as_view(), name='tree'),
    path('<int:pk>/', views.JobPage.as_view(), name='job'),
    path('quantile/<int:pk>/', views.JobQuantilePage.as_view(), name='quantile'),
    path('quantile/', views.JobQuantileSeveralPage.as_view()),
    path('decision_results/<int:pk>/', views.DecisionResults.as_view()),
    path('status/<int:pk>/', views.JobStatus.as_view()),
    path('scatter/<int:job1_id>/<int:job2_id>/', views.JobsScatterPage.as_view(), name='scatter'),

    # Main actions with jobs
    path('remove/', views.RemoveJobsView.as_view()),
    path('clear/', views.ClearJobsView.as_view()),
    path('save_job_copy/<int:pk>/', views.SaveJobCopyView.as_view()),
    path('decision_results_json/<int:pk>/', views.DecisionResultsJson.as_view()),
    path('set_attrs/<int:pk>/', views.SetJobViewAttrs.as_view()),

    # Job form
    re_path(r'^form/(?P<pk>[0-9]+)/(?P<action>edit|copy)/$', views.JobFormPage.as_view(), name='form'),
    path('get_version_data/<int:job_id>/<int:version>/', views.GetJobHistoryData.as_view()),
    path('get_version_roles/<int:job_id>/<int:version>/', views.GetJobHistoryRoles.as_view()),
    path('get_version_files/<int:job_id>/<int:version>/', views.GetJobHistoryFiles.as_view()),

    # Actions with job files
    path('downloadfile/<slug:hash_sum>/', views.DownloadJobFileView.as_view(), name='download_file'),
    path('upload_file/', views.UploadJobFileView.as_view()),
    path('getfilecontent/<slug:hashsum>/', views.GetFileContentView.as_view()),
    path('get_files_diff/<slug:hashsum1>/<slug:hashsum2>/', views.GetFilesDiffView.as_view()),
    path('replace_job_file/<int:job_id>/', views.ReplaceJobFileView.as_view()),
    path('downloadcompetfile/<int:pk>/', views.DownloadFilesForCompetition.as_view(), name='download_file_for_compet'),

    # Download/upload actions
    path('downloadjob/<int:pk>/', views.DownloadJobView.as_view(), name='download'),
    path('downloadjobs/', views.DownloadJobsListView.as_view()),
    path('downloadtrees/', views.DownloadJobsTreeView.as_view()),
    path('upload_jobs/<slug:parent_id>/', views.UploadJobsView.as_view()),
    path('upload_jobs_tree/', views.UploadJobsTreeView.as_view()),

    # Actions with job solving
    path('run_decision/<int:job_id>/', views.StartDecision.as_view()),
    path('stop_decision/<int:pk>/', views.StopDecisionView.as_view()),

    # "Utils"
    path('get_job_field/', views.GetJobFieldView.as_view()),
    path('do_job_has_children/<int:pk>/', views.DoJobHasChildrenView.as_view()),
    path('check_download_access/', views.CheckDownloadAccessView.as_view()),

    # Actions with reports
    path('upload_reports/<int:pk>/', views.UploadReportsView.as_view()),
]

web/marks/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path, re_path

from marks import views

urlpatterns = [
    # Main marks pages
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/$', views.MarkPage.as_view(), name='mark'),
    re_path(r'^(?P<type>unsafe|safe|unknown)/association_changes/(?P<association_id>.*)/$',
            views.AssociationChangesView.as_view()),
    re_path(r'^(?P<type>unsafe|safe|unknown)/$', views.MarksListView.as_view(), name='list'),

    # Mark form
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/(?P<action>create|edit)/$',
            views.MarkFormView.as_view(), name='mark_form'),
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/(?P<action>create|edit)/inline/$',
            views.InlineMarkForm.as_view()),

    # Mark versions views
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/remove_versions/$', views.RemoveVersionsView.as_view()),
    re_path(r'^(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/compare_versions/$', views.CompareVersionsView.as_view()),

    # Download/Upload marks
    re_path(r'^download/(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/$',
            views.DownloadMarkView.as_view(), name='download_mark'),
    re_path(r'^download-preset/(?P<type>unsafe|safe|unknown)/(?P<pk>[0-9]+)/$',
            views.DownloadPresetMarkView.as_view(), name='download_preset_mark'),
    path('upload/', views.UploadMarksView.as_view()),
    path('download-all/', views.DownloadAllMarksView.as_view(), name='download_all'),
    path('upload-all/', views.UploadAllMarksView.as_view()),

    # Tags
    path('tags/save_tag/', views.SaveTagView.as_view()),
    re_path(r'^tags/(?P<type>unsafe|safe)/$', views.TagsTreeView.as_view(), name='tags'),
    re_path(r'^tags/(?P<type>unsafe|safe)/download/$', views.DownloadTagsView.as_view(), name='download_tags'),
    re_path(r'^tags/(?P<type>unsafe|safe)/upload/$', views.UploadTagsView.as_view()),
    re_path(r'^tags/(?P<type>unsafe|safe)/get_tag_data/$', views.TagDataView.as_view()),
    re_path(r'^tags/(?P<type>unsafe|safe)/delete/(?P<pk>[0-9]+)/$', views.RemoveTagView.as_view()),
    re_path(r'^(?P<type>unsafe|safe)/tags_data/$', views.MarkTagsView.as_view()),

    # Action with associations
    re_path(r'^association/(?P<type>unsafe|safe|unknown)/(?P<rid>[0-9]+)/(?P<mid>[0-9]+)/(?P<act>confirm|unconfirm)/$',
            views.ChangeAssociationView.as_view()),

    # Utils
    path('delete/', views.DeleteMarksView.as_view()),
    path('get_func_description/<int:pk>/', views.GetFuncDescription.as_view()),
    path('get_progress/<int:pk>/', views.GetProgress.as_view()),
    path('get_last_mark/', views.GetLastMark.as_view()),
    path('get_converted_trace/<int:pk>/', views.GetConvertedTrace.as_view()),
    path('check-unknown-mark/<int:pk>/', views.CheckUnknownMarkView.as_view()),

    # Comments
    path('create-comment/', views.CreateComment.as_view()),
    path('delete-comment/', views.DeleteComment.as_view()),
    path('submit-review/', views.SubmitReview.as_view()),
    path('delete-review/', views.DeleteReview.as_view()),
]

web/tools/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path

from tools import views

urlpatterns = [
    path('manager/', views.manager_tools, name='manager'),
    path('view_call_logs/', views.view_call_logs, name='view_call_logs'),
    path('processing_list/', views.processing_list, name='processing_list'),
    path('ajax/rename_component/', views.rename_component),
    path('ajax/clear_components/', views.clear_components),
    path('ajax/clear_problems/', views.clear_problems),
    path('ajax/clear_system/', views.clear_system),
    path('ajax/resolve_marks/', views.resolve_marks),
    path('ajax/recalculation/', views.recalculation),
    path('ajax/call_list/', views.call_list),
    path('ajax/call_stat/', views.call_statistic),
    path('ajax/clear_call_logs/', views.clear_call_logs),
    path('ajax/clear_cet/', views.clear_cet),
    path('ajax/clear_all_cet/', views.clear_all_cet),
    path('ajax/clear_all_reviews/', views.clear_all_reviews),
    path('ajax/clear_jobs_view/', views.clear_jobs_view),
    path('ajax/clear_tasks/', views.clear_tasks),
    path('manual_unlock/', views.manual_unlock)
]

web/users/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.urls import path

from users import views

urlpatterns = [
    path('signin/', views.user_signin, name='login'),
    path('signout/', views.user_signout, name='logout'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('profile/<int:user_id>/', views.show_profile, name='show_profile'),
    path('comments/', views.show_comments, name='comments'),
    path('service_signin/', views.service_signin),
    path('service_signout/', views.service_signout),

    # View actions
    path('ajax/get_view/', views.get_view),
    path('ajax/save_view/', views.save_view),
    path('ajax/remove_view/', views.remove_view),
    path('ajax/share_view/', views.share_view),
    path('ajax/preferable_view/', views.preferable_view),
    path('ajax/check_view_name/', views.check_view_name),
]

web/web/urls.py
#
# CVV is a continuous verification visualizer.
# Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
# Ivannikov Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve

from web import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('jobs/', include(('jobs.urls', 'jobs'), namespace='jobs')),
    path('reports/', include(('reports.urls', 'reports'), namespace='reports')),
    path('marks/', include(('marks.urls', 'marks'), namespace='marks')),
    path('service/', include(('service.urls', 'service'), namespace='service')),
    path('tools/', include(('tools.urls', 'tools'), namespace='tools')),
    path('', views.index_page),
    path('population/', views.population, name='population'),
    path('help/<slug:page>/', views.help_pages, name='help'),
    path('get_help_pages/<slug:page>/', views.get_help_pages, name="get_help_pages"),
    path('help/', views.help_pages, name='help'),
    path('media/<path>', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})
]

web/templates/base.html
{% comment "License" %}
% CVV is a continuous verification visualizer.
% Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
{% endcomment %}

<!DOCTYPE html>

{% load static %}

{% load i18n %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/static/images/cv.png">
        <title>{% block title %}{% trans 'Sign in' %}{% endblock %} | CV</title>
        <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/notify.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'semantic/semantic.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/web.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/treetable.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>

        <link href="{% static 'semantic/semantic.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/web.css' %}" rel="stylesheet">
        <link href="{% static 'data_tables/css/jquery.dataTables.min.css' %}" rel="stylesheet">
        {% block head_block %}{% endblock %}
    </head>
    <body>
        {% if not standalone_html %}
        <div id="dimmer_of_page" class="ui dimmer">
            <div class="ui text loader">{% trans 'Please wait' %}</div>
        </div>

        <div id="page_header" class="ui inverted menu blue fixed">
            <div class="item" style="padding: 6px">
                <a {% if user.is_authenticated %}href="{% url 'jobs:tree' %}"{% endif %}>
                    <div title="{% trans 'Web-interface for Continuous Verification system' %}">
                        <img height="40" src="/static/images/cv_logo.png">
                    </div>
                </a>
            </div>
        {% if user.is_authenticated %}
            <div class="ui text menu compact" style="padding-left: 20px;">
                <a class="browse item">
                    <h4>{% trans 'Menu' %}<i class="dropdown icon"></i></h4>
                </a>
                <div class="ui flowing basic admission popup">
                    <div class="ui {% if user.is_staff or user.extended and user.extended.role == '2' %}four{% else %}three{% endif %} column divided grid">
                        <div class="blue column">
                            <h4 class="ui header" style="color:white">{% trans 'Jobs' %}</h4>
                            <div class="ui list">
                                <a class="item" href="{% url 'jobs:tree' %}">{% trans 'Jobs Tree' %}</a>
                                {% if user.extended.role == '2' or user.extended.role == '1' %}
                                    <a class="item" href="{% url 'service:launcher' %}">{% trans 'Launcher' %}</a>
                                {% endif %}
                                <!-- TODO: not supported
                                {% if user.extended.role == '2' or user.extended.role == '1' %}
                                    <a class="item" id="show_upload_job_popup">{% trans 'Upload jobs' %}</a>
                                {% endif %}
                                -->
                            </div>
                        </div>
                        <div class="column blue">
                            <h4 class="ui header" style="color:white">{% trans 'Marks' %}</h4>
                            <div class="ui list">
                                <a class="item" href="{% url 'marks:list' 'unsafe' %}">{% trans 'Unsafes' %}</a>
                                <a class="item" href="{% url 'marks:list' 'unknown' %}">{% trans 'Unknowns' %}</a>
                                <a class="item" href="{% url 'marks:list' 'safe' %}">{% trans 'Safes' %}</a>
                                <a class="item" href="{% url 'users:comments' %}">{% trans 'Comments' %}</a>
                            </div>
                        </div>
                        <div class="column blue">
                            <h4 class="ui header" style="color:white">{% trans 'Tags' %}</h4>
                            <div class="ui list">
                                <a class="item" href="{% url 'marks:tags' 'unsafe' %}">{% trans 'Unsafes' %}</a>
                                <a class="item" href="{% url 'marks:tags' 'safe' %}">{% trans 'Safes' %}</a>
                            </div>
                        </div>
                        {% if user.is_staff or user.extended and user.extended.role == '2' %}
                        <div class="column blue">
                            <h4 class="ui header" style="color:white">{% trans 'Admin' %}</h4>
                            <div class="ui list">
                                {% if user.is_staff %}
                                <a class="item" href="/admin/">{% trans 'Admin Tools' %}</a>
                                {% endif %}
                                {% if user.extended and user.extended.role == '2' %}
                                <a class="item" href="{% url 'tools:manager' %}">{% trans 'Manager Tools' %}</a>
                                {% endif %}
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
            <div class="right menu">
            {% if user.is_authenticated %}
                <a class="item" href="/help">{% trans 'About' %}</a>
                <a class="item" href="/help/{% block help_link %}{% endblock %}"><i class="ui icon question circle"></i></a>
                <div class="ui text menu right compact" style="padding-right: 20px; padding-top: 0px;">
                    <a class="browse item">
                        <h4>{{ user.username }}<i class="dropdown icon"></i></h4>
                    </a>
                    <div class="ui flowing basic popup">
                        <div class="ui one column divided grid">
                            <div class="column blue">
                                <a class="item" href="{% url 'users:show_profile' user.pk %}">{% trans 'Activity' %}</a>
                                <a class="item" href="{% url 'users:edit_profile' %}">{% trans 'Settings' %}</a>
                                <a class="item" href="{% url 'users:logout' %}">{% trans 'Sign Out' %}</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <a class="item" href="{% url 'users:register' %}">{% trans 'Register' %}</a>
                <a class="item" href="{% url 'users:login' %}">{% trans 'Sign In' %}</a>
            {% endif %}
            </div>
        </div>
        <br>
        {% endif %}
        {% block body_block %}{% endblock %}
        <div id="upload_job_popup" class="ui modal">
            <div class="header">{% trans 'Upload jobs' %}</div>
            <div class="content">
                <p>{% trans "Set parent identifier. All file or folder names with non-ASCII characters will be truncated to 30 characters." %}</p>
                <div class="ui grid">
                    <div class="five wide column">
                        <div class="ui fluid input">
                            <input id="upload_job_parent_id" type="text" placeholder="{% trans 'Identifier' %}" maxlength="32">
                        </div>
                    </div>
                    <div class="three wide column right aligned">
                        <span class="ui violet button btn-file">{% trans 'Browse' %}<input id="upload_job_file_input" type="file" multiple></span>
                    </div>
                    <div class="eight wide column">
                        <span id="upload_job_filename"></span>
                    </div>
                </div>
            </div>
            <div class="actions">
                <button id="upload_jobs_start" type="button" class="ui positive button">{% trans 'Upload' %}</button>
                <button id="upload_job_cancel" type="button" class="ui blue button">{% trans 'Cancel' %}</button>
            </div>
        </div>

        <div id="upload_jobtree_popup" class="ui modal">
            <div class="header">{% trans 'Upload jobs tree' %}</div>
            <div class="content">
                <p>{% trans "Set parent identifier or leave it empty for root jobs from tree to be without a parent." %}</p>
                <div class="ui grid">
                    <div class="five wide column">
                        <div class="ui fluid input">
                            <input id="upload_jobtree_parent_id" type="text" placeholder="{% trans 'Identifier' %}" maxlength="32">
                        </div>
                    </div>
                    <div class="three wide column right aligned">
                        <span class="ui violet button btn-file">{% trans 'Browse' %}<input id="upload_jobtree_file_input" type="file"></span>
                    </div>
                    <div class="eight wide column">
                        <span id="upload_jobtree_filename"></span>
                    </div>
                </div>
            </div>
            <div class="actions">
                <button id="upload_jobstree_start" type="button" class="ui positive button">{% trans 'Upload' %}</button>
                <button id="upload_jobstree_cancel" type="button" class="ui blue button">{% trans 'Cancel' %}</button>
            </div>
        </div>
        <span id="error__no_file_chosen" hidden>{% trans 'No file is chosen' %}</span>
        <span id="error__ajax_error" hidden>{% trans 'Ajax request error. Maybe connection refused.' %}</span>
        <span id="trans__sort_length_menu" hidden>{% trans 'Show _MENU_ rows' %}</span>
        <span id="trans__sort_info" hidden>{% trans 'Display from _START_ to _END_ of _TOTAL_ rows' %}</span>
        <span id="trans__sort_info_empty" hidden>{% trans 'Nothing is found' %}</span>
        <span id="trans__sort_info_filtered" hidden>({% trans 'filtered of _MAX_ rows' %})</span>
        <span id="trans__sort_search" hidden>{% trans 'Search' %}:</span>
        <span id="trans__sort_next" hidden>{% trans 'Next' %}</span>
        <span id="trans__sort_previous" hidden>{% trans 'Previous' %}</span>
        <span id="trans__sort_all" hidden>{% trans 'all' %}</span>
    </body>
</html>

web/templates/error.html
{% extends 'base.html' %}
{% comment "License" %}
% CVV is a continuous verification visualizer.
% Copyright (c) 2023 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Copyright (c) 2018 ISP RAS (http://www.ispras.ru)
% Ivannikov Institute for System Programming of the Russian Academy of Sciences
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
{% endcomment %}

{% load i18n %}

{% block title %}{% trans 'Error' %}{% endblock %}

{% block body_block %}
    {% if message %}
        <h1 style="color: #ef2f6c">{{ message }}</h1>
    {% endif %}
    {% if back %}
        <a class="ui teal button" href="{{ back }}">{% trans 'OK' %}</a>
    {% endif %}
{% endblock %}